/**
 * A fake backend for running the UI in a plain browser.
 *
 * `npm run dev` without Tauri is the fastest way to work on the interface —
 * no Rust rebuild, instant HMR, and browser devtools. This installs a stub
 * `__TAURI_INTERNALS__` so `invoke()` resolves with representative data.
 *
 * It is behind `import.meta.env.DEV` at the only call site, so Vite drops the
 * whole module from production builds. It never runs inside Tauri, because
 * Tauri defines `__TAURI_INTERNALS__` itself.
 */

import type {
  BrowseEntry,
  CleanupRecord,
  DirectoryListing,
  Protection,
  ScanReport,
  ScanResult,
} from "./types";

const MB = 1_000_000;
const GB = 1_000_000_000;

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 86_400_000).toISOString();
}

function result(
  scanner: string,
  title: string,
  path: string,
  size: number,
  risk: ScanResult["risk"],
  category: ScanResult["category"],
  description: string,
  idleDays: number,
  score: number,
): ScanResult {
  return {
    id: `${scanner}-${path}`,
    scanner,
    title,
    description,
    path,
    size,
    kind: "directory",
    fileCount: Math.round(size / 40_000),
    category,
    risk,
    deletable: risk !== "dangerous",
    recoverable: true,
    lastAccessed: daysAgo(idleDays),
    lastModified: daysAgo(idleDays),
    score,
    confidence: 0.9,
  };
}

const RESULTS: ScanResult[] = [
  result(
    "docker",
    "Docker — Images",
    "/docker/images",
    45 * GB,
    "review",
    "container",
    "Container images you have pulled or built. Docker reports 30 GB of this as reclaimable. Run `docker image prune -a` to reclaim it.",
    12,
    78,
  ),
  result(
    "node_modules",
    "~/code/old-api",
    "/Users/you/code/old-api/node_modules",
    18 * GB,
    "safe",
    "packageCache",
    "Dependencies for a project you last changed 412 days ago. Run `npm install` in that folder to bring them back.",
    412,
    74,
  ),
  result(
    "xcode_derived_data",
    "Xcode DerivedData — ~/Library/Developer/Xcode/DerivedData",
    "/Users/you/Library/Developer/Xcode/DerivedData",
    12 * GB,
    "safe",
    "buildArtifact",
    "Build artifacts generated by Xcode. Safe to remove — Xcode recreates them the next time you build, which takes longer that one time.",
    64,
    61,
  ),
  result(
    "downloads",
    "~/Downloads/Xcode_15.4.xip",
    "/Users/you/Downloads/Xcode_15.4.xip",
    9 * GB,
    "review",
    "downloads",
    "Files you downloaded and have not opened in a long time. Nothing here is recreated automatically, so check the list before removing anything.",
    398,
    44,
  ),
  result(
    "ollama_models",
    "Ollama models — ~/.ollama/models",
    "/Users/you/.ollama/models",
    7.4 * GB,
    "review",
    "aiModel",
    "AI models you downloaded to run locally. Each is a multi-gigabyte download that has to be fetched again from the internet if you want it back.",
    120,
    38,
  ),
  result(
    "app_cache",
    "Application caches — ~/Library/Caches",
    "/Users/you/Library/Caches",
    4.2 * GB,
    "safe",
    "cache",
    "Temporary files created by applications. They are recreated automatically the next time an app needs them — the app may open slightly slower once.",
    3,
    35,
  ),
  result(
    "chrome_cache",
    "Chrome cache — ~/Library/Caches/Google/Chrome",
    "/Users/you/Library/Caches/Google/Chrome",
    2.1 * GB,
    "safe",
    "browserCache",
    "Copies of web pages Chrome saved so they load faster. Chrome rebuilds this as you browse. Your history, passwords and bookmarks are not touched.",
    1,
    24,
  ),
  result(
    "duplicates",
    "~/Downloads/report copy.pdf",
    "/Users/you/Downloads/report copy.pdf",
    820 * MB,
    "review",
    "duplicate",
    "Identical to ~/Documents/report.pdf. That copy is kept; this one can go.",
    210,
    18,
  ),
  result(
    "large_files",
    "~/Movies/screen-recording.mov",
    "/Users/you/Movies/screen-recording.mov",
    640 * MB,
    "dangerous",
    "largeFile",
    "A large file. Check whether you still need it before removing it.",
    30,
    4,
  ),
];

function group(key: string, label: string, items: number, size: number) {
  return { key, label, items, size };
}

const REPORT: ScanReport = {
  id: "mock-scan",
  startedAt: daysAgo(0),
  durationMs: 8_420,
  cancelled: false,
  results: RESULTS,
  summary: {
    totalItems: RESULTS.length,
    totalSize: RESULTS.reduce((sum, r) => sum + r.size, 0),
    safeSize: RESULTS.filter((r) => r.risk === "safe").reduce((sum, r) => sum + r.size, 0),
    reviewSize: RESULTS.filter((r) => r.risk === "review").reduce((sum, r) => sum + r.size, 0),
    byCategory: [
      group("container", "Containers", 1, 45 * GB),
      group("packageCache", "Package caches", 1, 18 * GB),
      group("buildArtifact", "Build artifacts", 1, 12 * GB),
      group("downloads", "Downloads", 1, 9 * GB),
      group("aiModel", "AI models", 1, 7.4 * GB),
      group("cache", "Caches", 1, 4.2 * GB),
      group("browserCache", "Browser caches", 1, 2.1 * GB),
      group("duplicate", "Duplicates", 1, 820 * MB),
      group("largeFile", "Large files", 1, 640 * MB),
    ],
    byScanner: RESULTS.map((r) => group(r.scanner, r.scanner, 1, r.size)),
  },
  scanners: RESULTS.map((r) => ({
    scanner: r.scanner,
    name: r.scanner,
    status: "completed" as const,
    items: 1,
    size: r.size,
    durationMs: 400,
    message: null,
  })),
};

const CLEANUP: CleanupRecord = {
  id: "mock-cleanup",
  performedAt: daysAgo(2),
  mode: "trash",
  dryRun: false,
  freed: 12 * GB,
  removed: 3,
  skipped: 1,
  failed: 0,
  undoable: true,
  items: [],
};

/** A tiny in-memory filesystem so the explorer has something to walk. */
const TREE: Record<string, Array<[string, "file" | "directory", number, Protection]>> = {
  "/Users/you": [
    ["Library", "directory", 128 * GB, { kind: "allowed" }],
    ["code", "directory", 62 * GB, { kind: "allowed" }],
    ["Documents", "directory", 41 * GB, { kind: "caution", reason: "your documents" }],
    ["Pictures", "directory", 33 * GB, { kind: "caution", reason: "your photos" }],
    ["Downloads", "directory", 21 * GB, { kind: "allowed" }],
    ["Movies", "directory", 18 * GB, { kind: "caution", reason: "your videos" }],
    [".ollama", "directory", 7.4 * GB, { kind: "allowed" }],
    [".ssh", "directory", 24_000, { kind: "refused", reason: "the keys you use to sign in to other machines" }],
    [".config", "directory", 180 * MB, { kind: "refused", reason: "settings for the applications you use" }],
    ["Applications", "directory", 4 * GB, { kind: "refused", reason: "installed applications" }],
    ["notes.md", "file", 12_000, { kind: "allowed" }],
  ],
  "/Users/you/code": [
    ["old-api", "directory", 18 * GB, { kind: "allowed" }],
    ["dashboard", "directory", 16 * GB, { kind: "allowed" }],
    ["spacekeeper", "directory", 14 * GB, { kind: "allowed" }],
    ["experiments", "directory", 9 * GB, { kind: "allowed" }],
    ["scratch", "directory", 5 * GB, { kind: "allowed" }],
  ],
  "/Users/you/code/old-api": [
    ["node_modules", "directory", 17.4 * GB, { kind: "allowed" }],
    [".git", "directory", 540 * MB, { kind: "caution", reason: "a project's entire version history" }],
    ["src", "directory", 42 * MB, { kind: "allowed" }],
    ["package.json", "file", 2_400, { kind: "allowed" }],
  ],
  "/Users/you/Downloads": [
    ["Xcode_15.4.xip", "file", 9 * GB, { kind: "allowed" }],
    ["ubuntu-24.04.iso", "file", 5.8 * GB, { kind: "allowed" }],
    ["dataset.zip", "file", 4.1 * GB, { kind: "allowed" }],
    ["report copy.pdf", "file", 820 * MB, { kind: "allowed" }],
    ["screenshot.png", "file", 2.4 * MB, { kind: "allowed" }],
  ],
  "/Users/you/Library": [
    ["Caches", "directory", 74 * GB, { kind: "allowed" }],
    ["Developer", "directory", 38 * GB, { kind: "allowed" }],
    ["Application Support", "directory", 12 * GB, { kind: "allowed" }],
    ["Keychains", "directory", 8 * MB, { kind: "refused", reason: "your saved passwords" }],
  ],
};

function listing(path: string): DirectoryListing {
  const rows = TREE[path] ?? [];
  const total = rows.reduce((sum, [, , size]) => sum + size, 0);
  const entries: BrowseEntry[] = rows.map(([name, kind, size, protection]) => ({
    name,
    path: `${path}/${name}`,
    kind,
    // Files are known immediately; directories arrive unmeasured and are
    // filled in by the fake streaming pass below, like the real backend.
    size: kind === "file" ? size : 0,
    measured: kind === "file",
    fileCount: kind === "directory" ? Math.max(1, Math.round(size / 60_000)) : 1,
    share: total > 0 ? size / total : 0,
    lastAccessed: daysAgo(name === "old-api" ? 412 : 14),
    lastModified: daysAgo(name === "old-api" ? 412 : 14),
    protection,
    isSymlink: false,
  }));

  const segments = path.replace("/Users/you", "").split("/").filter(Boolean);
  let walked = "/Users/you";
  const breadcrumbs = [{ name: "you", path: walked }];
  for (const segment of segments) {
    walked = `${walked}/${segment}`;
    breadcrumbs.push({ name: segment, path: walked });
  }

  return {
    path,
    parent: path === "/Users/you" ? null : path.slice(0, path.lastIndexOf("/")),
    breadcrumbs,
    totalSize: total,
    entries,
    hiddenEntries: 0,
    protection:
      path === "/Users/you/Documents"
        ? { kind: "caution", reason: "your documents" }
        : { kind: "allowed" },
  };
}

const HANDLERS: Record<string, (args: Record<string, unknown>) => unknown> = {
  browse_directory: (args) => {
    const path = (args.path as string | null) ?? "/Users/you";
    const result = listing(path);
    // Stream the directory sizes back the way the real backend does, so the
    // progressive-loading path is exercised in the browser too.
    const token = ++browseToken;
    (TREE[path] ?? [])
      .filter(([, kind]) => kind === "directory")
      .forEach(([name, , size], index) => {
        setTimeout(
          () => {
            if (token !== browseToken) return;
            emit("browse://measured", {
              token,
              path: `${path}/${name}`,
              size,
              fileCount: Math.max(1, Math.round(size / 60_000)),
              lastAccessed: daysAgo(14),
              lastModified: daysAgo(14),
              crossesMount: false,
            });
          },
          150 + index * 120,
        );
      });
    return result;
  },
  delete_browsed: (args) => {
    const paths = (args.paths as string[]) ?? [];
    const dryRun = Boolean(args.dryRun);
    // Look the real size up in the fake tree so the dialog's total agrees with
    // the rows behind it — an inconsistency here reads as a bug in the app.
    const sizeOf = (path: string) => {
      const parent = path.slice(0, path.lastIndexOf("/"));
      const name = path.slice(path.lastIndexOf("/") + 1);
      return TREE[parent]?.find(([entry]) => entry === name)?.[2] ?? 0;
    };
    return {
      ...CLEANUP,
      dryRun,
      undoable: !dryRun && args.mode !== "permanent",
      removed: paths.length,
      freed: paths.reduce((sum, path) => sum + sizeOf(path), 0),
      skipped: 0,
      items: paths.map((path) => ({
        id: path,
        path,
        size: sizeOf(path),
        status: dryRun ? ("planned" as const) : ("trashed" as const),
        message: null,
      })),
    };
  },
  list_scanners: () => [
    {
      id: "app_cache",
      name: "Application caches",
      description: "Temporary data applications keep to start faster",
      explanation:
        "Temporary files created by applications. They are recreated automatically the next time an app needs them — the app may open slightly slower once.",
      family: "general",
      defaultRisk: "safe",
      platforms: ["macos", "linux", "windows"],
      enabledByDefault: true,
      requiresTool: null,
    },
    {
      id: "xcode_derived_data",
      name: "Xcode DerivedData",
      description: "Intermediate build output from Xcode",
      explanation:
        "Build artifacts generated by Xcode. Safe to remove — Xcode recreates them the next time you build, which takes longer that one time.",
      family: "developer",
      defaultRisk: "safe",
      platforms: ["macos"],
      enabledByDefault: true,
      requiresTool: "xcodebuild",
    },
    {
      id: "chrome_cache",
      name: "Chrome cache",
      description: "Web pages and images Chrome saved for faster loading",
      explanation:
        "Copies of web pages Chrome saved so they load faster. Chrome rebuilds this as you browse. Your history, passwords and bookmarks are not touched.",
      family: "browser",
      defaultRisk: "safe",
      platforms: ["macos", "linux", "windows"],
      enabledByDefault: true,
      requiresTool: null,
    },
    {
      id: "ollama_models",
      name: "Ollama models",
      description: "Local language models downloaded by Ollama",
      explanation:
        "AI models you downloaded to run locally. Each is a multi-gigabyte download that has to be fetched again from the internet if you want it back.",
      family: "ai",
      defaultRisk: "review",
      platforms: ["macos", "linux", "windows"],
      enabledByDefault: true,
      requiresTool: "ollama",
    },
  ],
  start_scan: () => REPORT,
  cancel_scan: () => null,
  pause_scan: () => null,
  resume_scan: () => null,
  scan_status: () => ({ paused: false, cancelled: false }),
  list_disks: () => [
    {
      name: "Macintosh HD",
      mountPoint: "/",
      fileSystem: "apfs",
      total: 494 * GB,
      available: 61 * GB,
      removable: false,
    },
  ],
  explain_disk: () => ({
    headline: `433 GB of 494 GB is in use. SpaceKeeper found ${Math.round(
      REPORT.summary.safeSize / GB,
    )} GB it can free safely.`,
    findings: [
      {
        scanner: "docker",
        sentence: "Docker is using 45 GB.",
        reason: "Worth a look before deleting — some of this may still be wanted.",
        size: 45 * GB,
        risk: "review" as const,
      },
      {
        scanner: "node_modules",
        sentence: "Node modules is using 18 GB.",
        reason: "These files are regenerated automatically when they are needed again.",
        size: 18 * GB,
        risk: "safe" as const,
      },
      {
        scanner: "xcode_derived_data",
        sentence: "Xcode DerivedData is using 12 GB.",
        reason: "These files are regenerated automatically when they are needed again.",
        size: 12 * GB,
        risk: "safe" as const,
      },
    ],
    safeTotal: REPORT.summary.safeSize,
    reviewTotal: REPORT.summary.reviewSize,
    nextSteps: [
      `Clean the safe items to reclaim ${Math.round(REPORT.summary.safeSize / GB)} GB — start with node_modules.`,
      `Review a further ${Math.round(REPORT.summary.reviewSize / GB)} GB of downloads and duplicates; these are kept until you decide.`,
      "Everything is moved to the Trash by default, so you can put it back.",
    ],
  }),
  total_freed: () => 87 * GB,
  scan_history: () =>
    [2, 9, 21, 44].map((days, index) => ({
      id: `scan-${index}`,
      startedAt: daysAgo(days),
      durationMs: 7_000 + index * 900,
      totalItems: 9 - index,
      totalSize: (99 - index * 7) * GB,
      safeSize: (34 - index * 3) * GB,
    })),
  cleanup_history: () => [CLEANUP],
  undo_supported: () => false,
  disk_trend: () =>
    Array.from({ length: 12 }, (_, index) => ({
      takenAt: daysAgo(33 - index * 3),
      total: 494 * GB,
      available: (48 + index * 1.2) * GB,
    })),
  scanner_stats: () =>
    RESULTS.map((r) => ({
      scanner: r.scanner,
      runs: 4,
      totalItems: 4,
      totalSize: r.size * 4,
      totalDurationMs: 1_600,
    })),
  get_settings: () => ({
    minResultSize: MB,
    largeFileThreshold: 256 * MB,
    staleAfterDays: 90,
    duplicateMinSize: MB,
    maxDepth: 12,
    disabledScanners: [],
    ignoredPaths: [],
  }),
  save_settings: (args) => args.options,
  ignored_paths: () => [],
  add_ignored_path: () => [],
  remove_ignored_path: () => [],
  protected_paths: () => [
    { path: "/System", reason: "part of macOS", refused: true },
    { path: "/Library", reason: "shared system files used by every account", refused: true },
    { path: "/Applications", reason: "installed applications", refused: true },
    { path: "/usr", reason: "part of the operating system", refused: true },
    { path: "/etc", reason: "system configuration", refused: true },
    { path: "/Users/you/.ssh", reason: "the keys you use to sign in to other machines", refused: true },
    { path: "/Users/you/.gnupg", reason: "your encryption keys", refused: true },
    { path: "/Users/you/.aws", reason: "cloud credentials", refused: true },
    { path: "/Users/you/.config", reason: "settings for the applications you use", refused: true },
    { path: "/Users/you/Library/Keychains", reason: "your saved passwords", refused: true },
    { path: "/Users/you/Documents", reason: "your documents", refused: false },
    { path: "/Users/you/Pictures", reason: "your photos", refused: false },
    { path: "/Users/you/Movies", reason: "your videos", refused: false },
    { path: "/Users/you/Music", reason: "your music", refused: false },
    { path: "/Users/you/Desktop", reason: "files you keep on your desktop", refused: false },
  ],
  reveal_path: () => null,
  preview_cleanup: (args) => {
    const command = args.command as { itemIds: string[]; mode: string };
    const chosen = RESULTS.filter((r) => command.itemIds.includes(r.id) && r.deletable);
    return {
      ...CLEANUP,
      dryRun: true,
      undoable: false,
      freed: chosen.reduce((sum, r) => sum + r.size, 0),
      removed: chosen.length,
      skipped: 0,
      items: chosen.map((r) => ({
        id: r.id,
        path: r.path,
        size: r.size,
        status: "planned" as const,
        message: null,
      })),
    };
  },
  run_cleanup: (args) => {
    const command = args.command as { itemIds: string[]; mode: "trash" | "permanent" };
    const chosen = RESULTS.filter((r) => command.itemIds.includes(r.id) && r.deletable);
    return {
      ...CLEANUP,
      mode: command.mode,
      undoable: command.mode === "trash",
      freed: chosen.reduce((sum, r) => sum + r.size, 0),
      removed: chosen.length,
      skipped: 0,
    };
  },
  undo_cleanup: () => [],
};

let browseToken = 0;

/** Listeners registered through Tauri's event bridge, by event name. */
const listeners = new Map<string, Set<(payload: unknown) => void>>();

function emit(event: string, payload: unknown): void {
  for (const handler of listeners.get(event) ?? []) handler(payload);
}

/** Install the stub. No-op inside Tauri, where the real bridge already exists. */
export function installDevMock(): void {
  if (typeof window === "undefined" || "__TAURI_INTERNALS__" in window) return;

  (window as unknown as Record<string, unknown>).__TAURI_INTERNALS__ = {
    // The event bridge: the mock never emits scan progress, so a scan simply
    // completes. Progress rendering is exercised by the real backend.
    transformCallback: (callback: unknown) => callback,
    invoke: async (command: string, args: Record<string, unknown> = {}) => {
      // Tauri's `listen()` routes through `invoke`, so the event bridge is
      // implemented here rather than as a normal command.
      if (command === "plugin:event|listen") {
        const event = args.event as string;
        const handler = args.handler as (payload: unknown) => void;
        const set = listeners.get(event) ?? new Set();
        set.add((payload) => handler({ event, id: 0, payload }));
        listeners.set(event, set);
        return 0;
      }

      const handler = HANDLERS[command];
      if (!handler) {
        // `plugin:event|listen` and friends arrive here; resolving keeps the
        // UI quiet rather than filling the console with unhandled rejections.
        return null;
      }
      // A small delay makes loading states visible while developing.
      await new Promise((resolve) => setTimeout(resolve, 120));
      return handler(args);
    },
  };

  // eslint-disable-next-line no-console
  console.info("[SpaceKeeper] dev mock backend installed — data on screen is fake.");
}
