//! The catalogue of declarative scanners.
//!
//! Every entry here becomes a scanner. Adding support for a new tool is a new
//! `PathRule` and nothing else.
//!
//! Two conventions keep this table honest:
//!
//! * `explanation` is written for someone who has never heard of the tool. It
//!   must say what the data is *and* what happens after it is deleted. "Build
//!   artifacts generated by Xcode" is only half an explanation; "…they are
//!   rebuilt the next time you build, which takes longer once" is the rest.
//! * `risk` is [`RiskLevel::Safe`] only when the owning application regenerates
//!   the data by itself. Anything the user would have to re-download, redo, or
//!   might actually want is [`RiskLevel::Review`].

use spacekeeper_core::{Category, Family, RiskLevel};

use crate::rules::PathRule;

const ALL: &[&str] = &["macos", "linux", "windows"];
const MAC: &[&str] = &["macos"];
const UNIX: &[&str] = &["macos", "linux"];
const LINUX: &[&str] = &["linux"];

/// Every declarative rule SpaceKeeper ships with.
pub const CATALOG: &[PathRule] = &[
    // ------------------------------------------------------------- general
    PathRule {
        id: "trash",
        name: "Trash",
        description: "Files you already deleted but that still take up space",
        explanation: "Items you moved to the Trash. They still occupy disk space until the Trash is emptied. Emptying it is permanent.",
        family: Family::General,
        category: Category::Trash,
        risk: RiskLevel::Review,
        confidence: 1.0,
        paths: &["~/.Trash", "~/.local/share/Trash/files", "~/.local/share/Trash/info"],
        exclude: &[],
        platforms: UNIX,
        requires_tool: None,
    },
    PathRule {
        id: "app_cache",
        name: "Application caches",
        description: "Temporary data applications keep to start faster",
        explanation: "Temporary files created by applications. They are recreated automatically the next time an app needs them — the app may open slightly slower once.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        // One result per application rather than one 40 GB blob: the user can
        // then clear Xcode's cache and keep Photos'.
        paths: &["~/Library/Caches/*", "~/.cache/*", "~/AppData/Local/Temp"],
        // Ceded to the scanners that can explain these specifically — they say
        // things like "your bookmarks are not touched", which a generic sweep
        // cannot. The engine would collapse the overlap safely either way; this
        // is about which explanation the user ends up reading.
        exclude: &[
            "Google", "google-chrome", "Chromium", "chromium", "Firefox", "mozilla",
            "com.apple.Safari", "Microsoft Edge", "microsoft-edge", "BraveSoftware",
            "Homebrew", "Yarn", "yarn", "pip", "JetBrains", "CocoaPods", "deno", "Godot",
            "godot", "go-build", "huggingface", "lm-studio", "composer", "gem",
            "vscode-cpptools", "com.spotify.client", "spotify", "Adobe",
            "com.unity3d.UnityEditor",
        ],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "app_logs",
        name: "Application logs",
        description: "Diagnostic logs written by applications",
        explanation: "Text files applications write to record what they did. They are only useful when troubleshooting a problem, and applications create new ones as needed.",
        family: Family::General,
        category: Category::Logs,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        // Per application, and ceding the folders that named rules explain
        // better — the same reasoning as the cache sweep above.
        paths: &["~/Library/Logs/*", "~/.local/state/log"],
        exclude: &["DiagnosticReports", "JetBrains"],
        platforms: UNIX,
        requires_tool: None,
    },
    PathRule {
        id: "crash_reports",
        name: "Crash reports",
        description: "Reports saved when an application quit unexpectedly",
        explanation: "Diagnostic reports saved when an app crashed. They are useful to a developer investigating that specific crash and to nobody else.",
        family: Family::General,
        category: Category::Logs,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Logs/DiagnosticReports", "~/Library/Application Support/CrashReporter"],
        exclude: &[],
        platforms: MAC,
        requires_tool: None,
    },

    // ----------------------------------------------------------- developer
    PathRule {
        id: "npm_cache",
        name: "npm cache",
        description: "Packages npm keeps so it can install them again offline",
        explanation: "Copies of packages npm has downloaded before. Deleting them means the next install downloads from the network again; nothing breaks.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/.npm/_cacache", "~/AppData/Local/npm-cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("npm"),
    },
    PathRule {
        id: "yarn_cache",
        name: "Yarn cache",
        description: "Packages Yarn keeps for offline installs",
        explanation: "Copies of packages Yarn has downloaded before. They are re-fetched automatically when a project needs them.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/Yarn", "~/.cache/yarn", "~/AppData/Local/Yarn/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("yarn"),
    },
    PathRule {
        id: "pnpm_store",
        name: "pnpm store",
        description: "pnpm's shared package store",
        explanation: "pnpm keeps one copy of every package version here and links projects to it. Removing it frees space but every project will re-download what it needs.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Review,
        confidence: 0.85,
        paths: &["~/Library/pnpm/store", "~/.local/share/pnpm/store", "~/.pnpm-store", "~/AppData/Local/pnpm/store"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("pnpm"),
    },
    PathRule {
        id: "cargo_cache",
        name: "Cargo registry cache",
        description: "Rust crates Cargo has downloaded",
        explanation: "Source code and archives of Rust packages Cargo downloaded. Cargo re-downloads whatever a project needs on the next build.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/.cargo/registry/cache", "~/.cargo/registry/src", "~/.cargo/git/checkouts"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("cargo"),
    },
    PathRule {
        id: "gradle_cache",
        name: "Gradle cache",
        description: "Dependencies and build state kept by Gradle",
        explanation: "Downloaded dependencies and build state for Java, Kotlin and Android projects. Gradle rebuilds this on the next build, which will take longer once.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/.gradle/caches", "~/.gradle/daemon"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("gradle"),
    },
    PathRule {
        id: "maven_repository",
        name: "Maven repository",
        description: "Java libraries downloaded by Maven",
        explanation: "Java libraries Maven downloaded for your projects. They are downloaded again on the next build if still needed.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Review,
        confidence: 0.8,
        paths: &["~/.m2/repository"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("mvn"),
    },
    PathRule {
        id: "nuget_packages",
        name: "NuGet packages",
        description: ".NET packages downloaded by NuGet",
        explanation: ".NET libraries NuGet downloaded. Restoring a project downloads what it needs again.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/.nuget/packages", "~/AppData/Local/NuGet/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("dotnet"),
    },
    PathRule {
        id: "pip_cache",
        name: "pip cache",
        description: "Python packages pip keeps for reinstalls",
        explanation: "Copies of Python packages pip downloaded. pip re-downloads them when needed.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/pip", "~/.cache/pip", "~/AppData/Local/pip/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("pip"),
    },
    PathRule {
        id: "go_module_cache",
        name: "Go module cache",
        description: "Go modules downloaded for your projects",
        explanation: "Go packages downloaded for building. `go build` fetches whatever it needs again.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/go/pkg/mod/cache/download", "~/Library/Caches/go-build", "~/.cache/go-build"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("go"),
    },
    PathRule {
        id: "homebrew_cache",
        name: "Homebrew cache",
        description: "Downloaded installers Homebrew keeps after installing",
        explanation: "Installer archives Homebrew downloaded. The software stays installed; only the downloaded copies are removed.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/Homebrew"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("brew"),
    },
    PathRule {
        id: "xcode_derived_data",
        name: "Xcode DerivedData",
        description: "Intermediate build output from Xcode",
        explanation: "Build artifacts generated by Xcode. Safe to remove — Xcode recreates them the next time you build, which takes longer that one time.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Safe,
        confidence: 0.98,
        paths: &["~/Library/Developer/Xcode/DerivedData"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("xcodebuild"),
    },
    PathRule {
        id: "xcode_device_support",
        name: "Xcode device support",
        description: "Debug symbols Xcode stores per iOS version",
        explanation: "Debugging files Xcode saved for each iOS version you connected a device with. Xcode re-creates them when you next connect that device.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/Library/Developer/Xcode/iOS DeviceSupport", "~/Library/Developer/Xcode/watchOS DeviceSupport"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("xcodebuild"),
    },
    PathRule {
        id: "xcode_archives",
        name: "Xcode archives",
        description: "Builds you archived for distribution",
        explanation: "Signed builds you archived, usually to submit to the App Store. These cannot be regenerated without rebuilding that exact version — review before deleting.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Review,
        confidence: 0.7,
        paths: &["~/Library/Developer/Xcode/Archives"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("xcodebuild"),
    },
    PathRule {
        id: "ios_simulators",
        name: "iOS Simulator data",
        description: "Disk images and caches for simulated devices",
        explanation: "Storage for the simulated iPhones and iPads Xcode runs. Deleting it resets those simulators to a clean state; the simulators themselves remain.",
        family: Family::Developer,
        category: Category::DeviceImage,
        risk: RiskLevel::Review,
        confidence: 0.75,
        paths: &["~/Library/Developer/CoreSimulator/Caches", "~/Library/Developer/CoreSimulator/Devices"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("simctl"),
    },
    PathRule {
        id: "android_sdk_images",
        name: "Android system images",
        description: "Emulator system images downloaded by Android Studio",
        explanation: "Copies of Android itself, used to run emulators. They can be downloaded again from Android Studio, but each one is a large download.",
        family: Family::Developer,
        category: Category::DeviceImage,
        risk: RiskLevel::Review,
        confidence: 0.8,
        paths: &["~/Library/Android/sdk/system-images", "~/Android/Sdk/system-images", "~/AppData/Local/Android/Sdk/system-images"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("sdkmanager"),
    },
    PathRule {
        id: "android_emulators",
        name: "Android emulator devices",
        description: "Virtual devices and their saved state",
        explanation: "The virtual Android phones you created, including anything installed inside them. Deleting these loses that state.",
        family: Family::Developer,
        category: Category::DeviceImage,
        risk: RiskLevel::Review,
        confidence: 0.6,
        paths: &["~/.android/avd", "~/.android/cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("emulator"),
    },
    PathRule {
        id: "cocoapods_cache",
        name: "CocoaPods cache",
        description: "iOS dependencies downloaded by CocoaPods",
        explanation: "Copies of iOS libraries CocoaPods downloaded. `pod install` fetches them again when needed.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/CocoaPods"],
        exclude: &[],
        platforms: MAC,
        requires_tool: Some("pod"),
    },
    PathRule {
        id: "jetbrains_cache",
        name: "JetBrains IDE caches",
        description: "Indexes and caches from IntelliJ, PyCharm and friends",
        explanation: "Search indexes JetBrains IDEs build for your projects. They are rebuilt on the next project open, which takes a few minutes once.",
        family: Family::Developer,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/Library/Caches/JetBrains", "~/.cache/JetBrains", "~/AppData/Local/JetBrains"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },

    PathRule {
        id: "vscode_cache",
        name: "VS Code caches",
        description: "Caches and cached extension data from Visual Studio Code",
        explanation: "Temporary data VS Code keeps to start faster. It is rebuilt automatically; your settings, extensions and projects are not affected.",
        family: Family::Developer,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &[
            "~/Library/Application Support/Code/Cache",
            "~/Library/Application Support/Code/CachedData",
            "~/Library/Application Support/Code/CachedExtensionVSIXs",
            "~/.cache/vscode-cpptools",
            "~/AppData/Roaming/Code/Cache",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("code"),
    },
    PathRule {
        id: "unity_cache",
        name: "Unity caches",
        description: "Asset and shader caches from the Unity editor",
        explanation: "Unity's imported copies of project assets. Unity rebuilds them the next time you open a project, which takes a few minutes once.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &[
            "~/Library/Unity/cache",
            "~/Library/Caches/com.unity3d.UnityEditor",
            "~/.local/share/unity3d/cache",
            "~/AppData/Local/Unity/cache",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("unity"),
    },
    PathRule {
        id: "godot_cache",
        name: "Godot cache",
        description: "Imported project data from the Godot engine",
        explanation: "Godot's imported copies of your project assets. They are regenerated when you next open the project.",
        family: Family::Developer,
        category: Category::BuildArtifact,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &["~/Library/Caches/Godot", "~/.cache/godot", "~/AppData/Local/Godot"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("godot"),
    },
    PathRule {
        id: "composer_cache",
        name: "Composer cache",
        description: "PHP packages downloaded by Composer",
        explanation: "Copies of PHP libraries Composer downloaded. `composer install` fetches whatever a project needs again.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/.composer/cache", "~/.cache/composer", "~/Library/Caches/composer"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("composer"),
    },
    PathRule {
        id: "ruby_gems_cache",
        name: "RubyGems cache",
        description: "Ruby gems downloaded for your projects",
        explanation: "Downloaded copies of Ruby libraries. `bundle install` fetches them again when a project needs them.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &["~/.bundle/cache", "~/.gem/cache", "~/.cache/gem"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("gem"),
    },
    PathRule {
        id: "bun_cache",
        name: "Bun cache",
        description: "Packages Bun keeps for faster installs",
        explanation: "Copies of packages Bun downloaded. They are re-fetched automatically when a project needs them.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/.bun/install/cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("bun"),
    },
    PathRule {
        id: "deno_cache",
        name: "Deno cache",
        description: "Modules Deno downloaded for your scripts",
        explanation: "Copies of modules Deno downloaded from the internet. They are fetched again the next time a script imports them.",
        family: Family::Developer,
        category: Category::PackageCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/deno", "~/.cache/deno", "~/AppData/Local/deno"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("deno"),
    },
    PathRule {
        id: "podman_cache",
        name: "Podman cache",
        description: "Container layer cache kept by Podman",
        explanation: "Intermediate container layers Podman keeps to make rebuilds faster. They are rebuilt on the next build.",
        family: Family::Developer,
        category: Category::Container,
        risk: RiskLevel::Review,
        confidence: 0.7,
        paths: &["~/.local/share/containers/cache"],
        exclude: &[],
        platforms: UNIX,
        requires_tool: Some("podman"),
    },
    PathRule {
        id: "jetbrains_logs",
        name: "JetBrains logs",
        description: "Diagnostic logs from IntelliJ, PyCharm and friends",
        explanation: "Logs JetBrains IDEs write while running. They matter only when reporting a bug and are recreated as needed.",
        family: Family::Developer,
        category: Category::Logs,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        // Linux JetBrains logs live under ~/.cache/JetBrains, which
        // `jetbrains_cache` already covers in full.
        paths: &["~/Library/Logs/JetBrains"],
        exclude: &[],
        platforms: MAC,
        requires_tool: None,
    },

    // ------------------------------------------------------- desktop apps
    PathRule {
        id: "slack_cache",
        name: "Slack cache",
        description: "Images and files Slack saved while you browsed",
        explanation: "Copies of images, files and messages Slack saved so they load faster. Slack re-downloads them as you scroll; nothing you sent or received is lost.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &[
            "~/Library/Application Support/Slack/Cache",
            "~/Library/Application Support/Slack/Service Worker/CacheStorage",
            "~/.config/Slack/Cache",
            "~/AppData/Roaming/Slack/Cache",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "discord_cache",
        name: "Discord cache",
        description: "Images and attachments Discord saved",
        explanation: "Copies of images and attachments Discord saved so they load faster. They are downloaded again as you scroll.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.9,
        paths: &[
            "~/Library/Application Support/discord/Cache",
            "~/Library/Application Support/discord/Code Cache",
            "~/.config/discord/Cache",
            "~/AppData/Roaming/discord/Cache",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "spotify_cache",
        name: "Spotify cache",
        description: "Music Spotify stored for offline and faster playback",
        explanation: "Songs Spotify saved locally so they start instantly. Removing them means streaming again over the network — downloaded playlists will need re-downloading.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Review,
        confidence: 0.7,
        paths: &[
            "~/Library/Caches/com.spotify.client",
            "~/Library/Application Support/Spotify/PersistentCache",
            "~/.cache/spotify",
            "~/AppData/Local/Spotify/Storage",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "adobe_cache",
        name: "Adobe media cache",
        description: "Preview files generated by Adobe applications",
        explanation: "Preview and waveform files Adobe apps generate while editing. They are rebuilt when you reopen a project, which takes time but loses no work.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &[
            "~/Library/Caches/Adobe",
            "~/Library/Application Support/Adobe/Common/Media Cache Files",
            "~/Library/Application Support/Adobe/Common/Media Cache",
            "~/AppData/Roaming/Adobe/Common/Media Cache Files",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "steam_downloads",
        name: "Steam download cache",
        description: "Partially downloaded and unpacked game files",
        explanation: "Temporary files Steam keeps while installing or updating games. Steam re-downloads what it needs; installed games are not affected.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &[
            "~/Library/Application Support/Steam/steamapps/downloading",
            "~/Library/Application Support/Steam/steamapps/shadercache",
            "~/.steam/steam/steamapps/downloading",
            "~/.local/share/Steam/steamapps/shadercache",
        ],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("steam"),
    },
    PathRule {
        id: "flatpak_cache",
        name: "Flatpak application caches",
        description: "Caches belonging to sandboxed Flatpak applications",
        explanation: "Temporary data Flatpak applications keep inside their sandboxes. Each application recreates what it needs.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &["~/.var/app/*/cache"],
        exclude: &[],
        platforms: LINUX,
        requires_tool: Some("flatpak"),
    },
    PathRule {
        id: "snap_cache",
        name: "Snap application caches",
        description: "Caches belonging to Snap applications",
        explanation: "Temporary data Snap applications keep. Each application recreates what it needs.",
        family: Family::General,
        category: Category::Cache,
        risk: RiskLevel::Safe,
        confidence: 0.85,
        paths: &["~/snap/*/common/.cache"],
        exclude: &[],
        platforms: LINUX,
        requires_tool: Some("snap"),
    },

    // ------------------------------------------------------------ browsers
    PathRule {
        id: "chrome_cache",
        name: "Chrome cache",
        description: "Web pages and images Chrome saved for faster loading",
        explanation: "Copies of web pages Chrome saved so they load faster. Chrome rebuilds this as you browse. Your history, passwords and bookmarks are not touched.",
        family: Family::Browser,
        category: Category::BrowserCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/Google/Chrome", "~/.cache/google-chrome", "~/AppData/Local/Google/Chrome/User Data/Default/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "firefox_cache",
        name: "Firefox cache",
        description: "Web pages and images Firefox saved for faster loading",
        explanation: "Copies of web pages Firefox saved so they load faster. Rebuilt as you browse; your history, passwords and bookmarks are not touched.",
        family: Family::Browser,
        category: Category::BrowserCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/Firefox/Profiles/*", "~/.cache/mozilla/firefox/*", "~/AppData/Local/Mozilla/Firefox/Profiles/*"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "safari_cache",
        name: "Safari cache",
        description: "Web pages and images Safari saved for faster loading",
        explanation: "Copies of web pages Safari saved so they load faster. Rebuilt as you browse; your history, passwords and bookmarks are not touched.",
        family: Family::Browser,
        category: Category::BrowserCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/com.apple.Safari", "~/Library/Containers/com.apple.Safari/Data/Library/Caches"],
        exclude: &[],
        platforms: MAC,
        requires_tool: None,
    },
    PathRule {
        id: "edge_cache",
        name: "Edge cache",
        description: "Web pages and images Edge saved for faster loading",
        explanation: "Copies of web pages Edge saved so they load faster. Rebuilt as you browse; your history, passwords and bookmarks are not touched.",
        family: Family::Browser,
        category: Category::BrowserCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/Microsoft Edge", "~/.cache/microsoft-edge", "~/AppData/Local/Microsoft/Edge/User Data/Default/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "brave_cache",
        name: "Brave cache",
        description: "Web pages and images Brave saved for faster loading",
        explanation: "Copies of web pages Brave saved so they load faster. Rebuilt as you browse; your history, passwords and bookmarks are not touched.",
        family: Family::Browser,
        category: Category::BrowserCache,
        risk: RiskLevel::Safe,
        confidence: 0.95,
        paths: &["~/Library/Caches/BraveSoftware", "~/.cache/BraveSoftware", "~/AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/Cache"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },

    // ------------------------------------------------------------------ ai
    PathRule {
        id: "ollama_models",
        name: "Ollama models",
        description: "Local language models downloaded by Ollama",
        explanation: "AI models you downloaded to run locally. Each is a multi-gigabyte download that has to be fetched again from the internet if you want it back.",
        family: Family::Ai,
        category: Category::AiModel,
        risk: RiskLevel::Review,
        confidence: 0.7,
        paths: &["~/.ollama/models"],
        exclude: &[],
        platforms: ALL,
        requires_tool: Some("ollama"),
    },
    PathRule {
        id: "lm_studio_models",
        name: "LM Studio models",
        description: "Local language models downloaded by LM Studio",
        explanation: "AI models downloaded through LM Studio. Removing one means downloading it again to use it.",
        family: Family::Ai,
        category: Category::AiModel,
        risk: RiskLevel::Review,
        confidence: 0.7,
        paths: &["~/.lmstudio/models", "~/.cache/lm-studio/models"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "huggingface_cache",
        name: "Hugging Face cache",
        description: "Models and datasets downloaded from Hugging Face",
        explanation: "Models and datasets Python tools downloaded from Hugging Face. They are re-downloaded automatically the next time a script asks for them.",
        family: Family::Ai,
        category: Category::AiModel,
        risk: RiskLevel::Review,
        confidence: 0.8,
        paths: &["~/.cache/huggingface/hub", "~/Library/Caches/huggingface/hub", "~/AppData/Local/huggingface/hub"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
    PathRule {
        id: "comfyui_models",
        name: "ComfyUI models",
        description: "Image generation models used by ComfyUI",
        explanation: "Image-generation model files. These are large and often hand-picked, so they are never removed without your explicit review.",
        family: Family::Ai,
        category: Category::AiModel,
        risk: RiskLevel::Review,
        confidence: 0.6,
        paths: &["~/ComfyUI/models", "~/comfyui/models"],
        exclude: &[],
        platforms: ALL,
        requires_tool: None,
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::{HashMap, HashSet};

    #[test]
    fn ids_are_unique() {
        let mut seen = HashSet::new();
        for rule in CATALOG {
            assert!(seen.insert(rule.id), "duplicate scanner id: {}", rule.id);
        }
    }

    #[test]
    fn every_rule_has_at_least_one_path_and_platform() {
        for rule in CATALOG {
            assert!(!rule.paths.is_empty(), "{} has no paths", rule.id);
            assert!(!rule.platforms.is_empty(), "{} has no platforms", rule.id);
        }
    }

    #[test]
    fn every_rule_explains_itself_in_plain_language() {
        for rule in CATALOG {
            assert!(!rule.name.is_empty(), "{} has no name", rule.id);
            assert!(
                rule.explanation.len() > 40,
                "{} needs a real explanation, not a label",
                rule.id
            );
            assert!(
                !rule.explanation.contains("DerivedData") || rule.explanation.contains("Xcode"),
                "{} uses jargon without explaining it",
                rule.id
            );
        }
    }

    #[test]
    fn confidence_is_a_probability() {
        for rule in CATALOG {
            assert!(
                (0.0..=1.0).contains(&rule.confidence),
                "{} has an out-of-range confidence",
                rule.id
            );
        }
    }

    #[test]
    fn no_rule_targets_a_bare_home_or_root() {
        for rule in CATALOG {
            for path in rule.paths {
                assert!(
                    *path != "~" && *path != "~/" && *path != "/",
                    "{} targets the whole home directory",
                    rule.id
                );
            }
        }
    }

    #[test]
    fn no_rule_uses_parent_directory_traversal() {
        for rule in CATALOG {
            for path in rule.paths {
                assert!(!path.contains(".."), "{} uses `..` in a path", rule.id);
            }
        }
    }

    #[test]
    fn nothing_that_needs_re_downloading_is_marked_safe() {
        // Models and simulator images are always Review: they cost the user a
        // large download or lose state, so they never get one-click deletion.
        for rule in CATALOG {
            if matches!(rule.category, Category::AiModel | Category::DeviceImage) {
                assert_eq!(
                    rule.risk,
                    RiskLevel::Review,
                    "{} must not be one-click deletable",
                    rule.id
                );
            }
        }
    }

    /// Literal (non-wildcard) paths a rule claims, with a `*` prefix kept as
    /// the parent so overlap can be reasoned about.
    fn literal_paths(rule: &PathRule) -> Vec<&'static str> {
        rule.paths.iter().copied().filter(|p| !p.contains('*')).collect()
    }

    #[test]
    fn no_two_rules_claim_exactly_the_same_path() {
        let mut seen: HashMap<&str, &str> = HashMap::new();
        for rule in CATALOG {
            for path in literal_paths(rule) {
                if let Some(other) = seen.insert(path, rule.id) {
                    panic!("{} and {} both claim {path}", other, rule.id);
                }
            }
        }
    }

    #[test]
    fn a_wildcard_sweep_cedes_every_folder_a_named_rule_owns() {
        // Without this, the broad sweep and the specific scanner both report
        // the same bytes. The engine collapses that safely, but the user ends
        // up reading the vaguer of the two explanations — so the sweep has to
        // name what it is giving up.
        for sweep in CATALOG {
            for pattern in sweep.paths.iter().filter(|p| p.ends_with("/*")) {
                let parent = pattern.trim_end_matches("/*");

                for other in CATALOG.iter().filter(|r| r.id != sweep.id) {
                    for path in literal_paths(other) {
                        let Some(rest) = path.strip_prefix(parent).and_then(|r| r.strip_prefix('/'))
                        else {
                            continue;
                        };
                        let owned = rest.split('/').next().unwrap_or(rest);
                        assert!(
                            sweep.exclude.iter().any(|e| e.eq_ignore_ascii_case(owned)),
                            "{} sweeps {parent}/* but does not exclude `{owned}`, which {} owns",
                            sweep.id,
                            other.id,
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn no_rule_is_nested_inside_another_rules_literal_path() {
        // A rule reporting a folder inside another rule's folder is double
        // counted until the engine merges it, and the merge always keeps the
        // outer one — so the inner rule would silently never be seen.
        for rule in CATALOG {
            for path in literal_paths(rule) {
                for other in CATALOG.iter().filter(|r| r.id != rule.id) {
                    for other_path in literal_paths(other) {
                        assert!(
                            !(path.starts_with(other_path)
                                && path.len() > other_path.len()
                                && path.as_bytes()[other_path.len()] == b'/'),
                            "{} claims {path}, which is inside {}'s {other_path}",
                            rule.id,
                            other.id,
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn platform_lists_contain_only_known_platforms() {
        for rule in CATALOG {
            for platform in rule.platforms {
                assert!(
                    ["macos", "linux", "windows"].contains(platform),
                    "{} lists unknown platform {platform}",
                    rule.id
                );
            }
        }
    }

    #[test]
    fn the_catalog_covers_every_family() {
        let families: HashSet<_> = CATALOG.iter().map(|r| r.family).collect();
        assert!(families.contains(&Family::General));
        assert!(families.contains(&Family::Developer));
        assert!(families.contains(&Family::Browser));
        assert!(families.contains(&Family::Ai));
    }
}
